version: '3.7'
services:
    # MongoDB Server
    mongo:
        image: mongo:6.0.2
        container_name: bio_api_mongo_db
        volumes:
            - mongo_data:/data/db
            - mongo_config:/data/configdb
            # Uncomment if you want custom MongoDB config
            # - ./config/mongo/mongod.conf:/etc/mongo/mongod.conf
        environment:
            MONGO_INITDB_ROOT_USERNAME: '' # Complete
            MONGO_INITDB_ROOT_PASSWORD: '' # Complete
            MONGO_INITDB_DATABASE: bio_api # Don't change this value!
        deploy:
            resources:
                limits:
                    memory: 6g

    # BioAPI server
    web:
        image: omicsdatascience/bio-api:1.0.2
        volumes:
            - bioapi_logs:/logs
        environment:
            DEBUG: 'false'
            # MongoDB's credentials must be the same as 'mongo' service above
            MONGO_HOST: 'mongo' # Change if needed
            MONGO_PORT: '27017' # Change if needed
            MONGO_USER: '' # Complete
            MONGO_PASSWORD: '' # Complete
            MONGO_DB: bio_api # Don't change this value!

    # NGINX server
    nginx:
        image: nginx:1.19.3
        ports:
            - 80:8000
        depends_on:
            - web
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d

volumes:
    mongo_data:
        external: true
        name: 'bio_api_mongo_data'
    mongo_config:
        external: true
        name: 'bio_api_mongo_config'
    bioapi_logs:
