services:
    # MongoDB Server
    mongo_bioapi:
        image: mongo:6.0.12
        container_name: bio_api_mongo_db
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'root'
            MONGO_INITDB_ROOT_PASSWORD: 'root'
            MONGO_INITDB_DATABASE: bio_api
        ports:
            - '27018:27017'
        volumes:
            # Mounts initialize script as read-only
            - mongo_data:/data/db
            - mongo_config:/data/configdb
            # Uncomment if you want custom MongoDB config
            # - ./config/mongo/mongod.conf:/etc/mongo/mongod.conf
        deploy:
            resources:
                limits:
                    memory: 6g

volumes:
    mongo_data:
        external: true
        name: 'bio_api_mongo_data'
    mongo_config:
        external: true
        name: 'bio_api_mongo_config'
