version: '3.7'
services:
    # MongoDB Server
    mongo:
        image: mongo:4.2
        container_name: bio_api_mongo_db
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db
            - mongo_data:/data/configdb
        environment:
            MONGO_INITDB_ROOT_USERNAME: '' # Complete
            MONGO_INITDB_ROOT_PASSWORD: '' # Complete
            MONGO_INITDB_DATABASE: bio_api # Change if needed

    # Flask server
    web:
        image: omicsdatascience/bio-api:0.1.0
        environment:
            DEBUG: 'false'

            # MongoDB's credentials must be the same as 'mongo' service above
            MONGO_HOST: 'mongo' # Change if needed
            MONGO_PORT: '27017' # Change if needed
            MONGO_USER: '' # Complete
            MONGO_PASSWORD: '' # Complete
            MONGO_DB: bio_api # Change if needed

    # NGINX server
    nginx:
        image: nginx:1.19.3
        ports:
            - 80:8000
        depends_on:
            - web
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d

volumes:
    mongo_data:
        external:
            name: 'bio_api_mongo_data'
    mongo_config:
        external:
            name: 'bio_api_mongo_config'
